<template>
  <div>
    <h1 style="margin-top:20px;" />
    <v-card light>
      Signup
      <v-col class="d-flex justify-center" />
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <v-text-field
          label="Outlined"
          outlined
          dense
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <v-text-field
          label="Outlined"
          outlined
          dense
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <v-text-field
          label="Outlined"
          outlined
          dense
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <v-text-field
          label="Outlined"
          outlined
          dense
        />
      </v-col>
      <v-col
        cols="12"
        sm="6"
        md="4"
      >
        <v-text-field
          label="Outlined"
          outlined
          dense
        />
      </v-col>
    </v-card>
  </div>
</template>

<style>

</style>
